'use client';
import { FormEvent, useState } from 'react';
import { buildWhatsAppUrl } from '@/lib/whatsapp';
import { siteConfig } from '@/data/site';
import { Facebook, Instagram, Youtube, MapPin, Phone, MessageCircle } from 'lucide-react';

export default function Contact(){
  const [form,setForm]=useState({name:'',phone:'',location:'Sankarankovil',acType:'Split AC',problem:'AC Not Cooling',preferredTime:'',message:''});
  const update=(k:string,v:string)=>setForm({...form,[k]:v});
  const submit=(e:FormEvent)=>{e.preventDefault(); window.open(buildWhatsAppUrl(form),'_blank','noopener,noreferrer');};
  return <section id="contact" className="section-pad section-break section-contact"><div className="container-site grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
    <div className="glass rounded-[2rem] p-7"><p className="text-sm font-bold uppercase tracking-[.3em] text-sky-300">Contact</p><h2 className="mt-3 text-4xl font-black">Book. Chat. Cool.</h2><p className="mt-4 leading-7 text-slate-400">Submit the form and we’ll open WhatsApp with all enquiry details pre-filled.</p><div className="mt-8 space-y-4 text-slate-300"><a className="flex items-center gap-3" href={`tel:${siteConfig.phone.replace(/\s/g,'')}`}><Phone className="text-sky-300"/> {siteConfig.phone}</a><a className="flex items-center gap-3" href={`https://wa.me/${siteConfig.whatsappNumber}`} target="_blank"><MessageCircle className="text-sky-300"/> WhatsApp</a><div className="flex items-center gap-3"><MapPin className="text-sky-300"/> {siteConfig.address}</div></div><div className="mt-8 flex gap-3"><a className="glass rounded-xl p-3" href={siteConfig.social.facebook} target="_blank"><Facebook/></a><a className="glass rounded-xl p-3" href={siteConfig.social.instagram} target="_blank"><Instagram/></a><a className="glass rounded-xl p-3" href={siteConfig.social.youtube} target="_blank"><Youtube/></a><a className="glass rounded-xl p-3 text-xs font-bold" href={siteConfig.social.googleBusiness} target="_blank">Google</a></div></div>
    <form onSubmit={submit} className="glass rounded-[2rem] p-6 md:p-8"><div className="grid gap-4 md:grid-cols-2"><input required placeholder="Your name" value={form.name} onChange={e=>update('name',e.target.value)}/><input required placeholder="Mobile number" value={form.phone} onChange={e=>update('phone',e.target.value)}/><input required placeholder="Location" value={form.location} onChange={e=>update('location',e.target.value)}/><select value={form.acType} onChange={e=>update('acType',e.target.value)}><option>Split AC</option><option>Window AC</option><option>Cassette AC</option><option>Other</option></select><select value={form.problem} onChange={e=>update('problem',e.target.value)}><option>AC Not Cooling</option><option>Water Leakage</option><option>AC Making Noise</option><option>AC Not Starting</option><option>Gas Filling</option><option>Installation</option><option>General Service</option><option>Other</option></select><input placeholder="Preferred time" value={form.preferredTime} onChange={e=>update('preferredTime',e.target.value)}/></div><textarea className="mt-4 min-h-32" placeholder="Additional message" value={form.message} onChange={e=>update('message',e.target.value)}/><button className="mt-4 w-full rounded-2xl bg-sky-300 px-5 py-4 font-black text-slate-950">Send Enquiry on WhatsApp</button></form>
  </div></section>
}
